name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Find and Build APK with Gradle
      run: |
        # Busca dónde está el archivo gradlew en el proyecto
        GRADLEW_PATH=$(find . -name "gradlew" -type f -print -quit)
        
        if [ -z "$GRADLEW_PATH" ]; then
          echo "¡No se encontró el archivo gradlew en ningún lado!"
          exit 1
        fi
        
        # Obtiene la carpeta donde está el gradlew
        GRADLEW_DIR=$(dirname "$GRADLEW_PATH")
        echo "¡Encontrado en la carpeta: $GRADLEW_DIR!"
        
        cd "$GRADLEW_DIR"
        chmod +x gradlew
        ./gradlew assembleRelease --no-daemon

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: '**/build/outputs/apk/release/*.apk'
